apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: inventory-quarkus-cnw3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: inventory-quarkus-cnw3
    app.kubernetes.io/part-of: cnw3
  name: inventory-quarkus-cnw3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: inventory-quarkus-cnw3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: inventory-quarkus-cnw3
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/agroom-tenant/cnw3/inventory-quarkus-cnw3@sha256:95373d41e7ce1b442c061bf9590cc4fbd04fffc2eeff0cf3ec6887bf4e7849e9
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
